### ISSUE TITLE
运行报错：ImportError: DLL load failed: 找不到指定的程序。

### ISSUE THREAD

**Issue by batumgl** [594422814/TransformerTrack#17]
C:\Users\Administrator\anaconda3\envs\pytracking\python.exe E:/TransformerTrack-main/pytracking/run_video.py
C:\Users\Administrator\anaconda3\envs\pytracking\lib\site-packages\torch\nn\functional.py:2973: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "E:/TransformerTrack-main/pytracking/run_video.py", line 38, in <module>
    main()
  File "E:/TransformerTrack-main/pytracking/run_video.py", line 34, in main
    run_video(args.tracker_name, args.tracker_param,args.videofile, args.optional_box, args.debug, args.save_results)
  File "E:/TransformerTrack-main/pytracking/run_video.py", line 20, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug, save_results=save_results)
  File "E:\TransformerTrack-main\pytracking\evaluation\tracker.py", line 293, in run_video
    tracker.initialize(frame, _build_init_info(init_state))
  File "E:\TransformerTrack-main\pytracking\evaluation\multi_object_wrapper.py", line 114, in initialize
    out = self.trackers[obj_id].initialize(image, init_info_split[obj_id])
  File "E:\TransformerTrack-main\pytracking\tracker\trdimp\trdimp.py", line 89, in initialize
    self.init_classifier(init_backbone_feat)
  File "E:\TransformerTrack-main\pytracking\tracker\trdimp\trdimp.py", line 617, in init_classifier
    compute_losses=plot_loss)
  File "E:\TransformerTrack-main\ltr\models\target_classifier\linear_filter.py", line 114, in get_filter
    weights = self.filter_initializer(feat, bb)
  File "C:\Users\Administrator\anaconda3\envs\pytracking\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\TransformerTrack-main\ltr\models\target_classifier\initializer.py", line 164, in forward
    weights = self.filter_pool(feat, bb)
  File "C:\Users\Administrator\anaconda3\envs\pytracking\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\TransformerTrack-main\ltr\models\target_classifier\initializer.py", line 45, in forward
    return self.prroi_pool(feat, roi1)
  File "C:\Users\Administrator\anaconda3\envs\pytracking\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\TransformerTrack-main\ltr\external\PreciseRoIPooling\pytorch\prroi_pool\prroi_pool.py", line 28, in forward
    return prroi_pool2d(features, rois, self.pooled_height, self.pooled_width, self.spatial_scale)
  File "E:\TransformerTrack-main\ltr\external\PreciseRoIPooling\pytorch\prroi_pool\functional.py", line 77, in forward
    _prroi_pooling = _import_prroi_pooling()
  File "E:\TransformerTrack-main\ltr\external\PreciseRoIPooling\pytorch\prroi_pool\functional.py", line 56, in _import_prroi_pooling
    _prroi_pooling = imp.load_module('prroi_pool', file, path, description)
  File "C:\Users\Administrator\anaconda3\envs\pytracking\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Administrator\anaconda3\envs\pytracking\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: 找不到指定的程序。
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!

进程已结束，退出代码 1

环境：
win10
python 3.7
torch 1.5.1
torchvision 0.6.0
cuda 10.1
ninja 1.10.2

Visual C++ Redistributable for Visual Studio 2015 已安装
Anaconda3\envs\pytracking\Lib\site-packages\torch\lib 已添加至环境变量
prroi_pool.pyd 已添加至对应文件夹
functional.py 代码已修改

**Comment by yuandongbo123** [comment]
把cuda 降到10.0
并且 pytorch降到1.2.0
python 3.7
亲测有效
产生的原因应该是dimp的里的imp.load_module函数，但是换成importlib.load_module也不行。
有知道大佬可以交流下吗？

**Comment by STAR-811** [comment]
把加的三行代码换成这个：
```
import importlib
spec = importlib.util.find_spec('prroi_pool')
_prroi_pooling = importlib.util.module_from_spec(spec)
```
