### ISSUE TITLE
使用got10k的测试工具报错

### ISSUE THREAD

**Issue by 1145284121** [594422814/TransformerTrack#31]
![image](https://user-images.githubusercontent.com/41956449/145704185-b4082dc0-8463-4f7f-a644-64430218d63b.png)
segmentation_dir:   /trdimp/trdimp_vot
Files already downloaded.
Running tracker GOT_Tracker on VOT...
Running supervised experiment...
--Sequence 1/60: ants1
 Repetition: 1
Traceback (most recent call last):
  File "GOT10k_VOT.py", line 45, in <module>
    experiment.run(tracker, visualize=False)
  File "/home/admin312/anaconda3/envs/pytracking/lib/python3.7/site-packages/got10k/experiments/vot.py", line 71, in run
    self.run_supervised(tracker, visualize)
  File "/home/admin312/anaconda3/envs/pytracking/lib/python3.7/site-packages/got10k/experiments/vot.py", line 126, in run_supervised
    tracker.init(frame, anno_rects[0])
  File "GOT10k_VOT.py", line 32, in init
    self.tracker.initialize(image, box)
  File "../pytracking/tracker/trdimp/trdimp.py", line 55, in initialize
    state = info['init_bbox']
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

看上去是版本导致的错误？  请问作者有遇到过或者有修改的思路吗

**Comment by 1145284121** [comment]
To run and evaluate the tracker using GOT-10k toolkit, you have to modify the ```/tracker/trdimp/trdimp.py``` to ensure it supports the input and output formats of GOT-10k toolkit. ```/tracker/trdimp/trdimp_for_GOT.py``` is an example.
